name: Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup k3s
        run: curl -sfL https://get.k3s.io | sh -
      - name: set kubeconfig
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: sudo mkdir ~/.kube && sudo cp ${KUBECONFIG} ~/.kube/config
      - name: test
        run: |
          sleep 10
          sudo kubectl get nodes
          sudo kubectl get pod -A
      - name: helminstall
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
     
