name: Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup k3s
        run: curl -sfL https://get.k3s.io | sh -
      - name: set kubeconfig
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: sudo mkdir ~/.kube && sudo cp ${KUBECONFIG} ~/.kube/config
      - name: test
        run: |
          sleep 10
          sudo kubectl get nodes -o wide
          sudo kubectl get pod -A
      - name: helminstall
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
      - name: create secret
        run: | 
          sudo kubectl create secret docker-registry directoronprem-registry-secret --docker-server=registry.mayadata.io --docker-username=${{ secrets.DOCKER_USERNAME }} --docker-password=${{ secrets.DOCKER_PASSWORD }}
          sudo kubectl get secret
      - name: kubera install
        run: |    
          IP=$(sudo kubectl get nodes -o wide --no-headers | awk {'print $6'} | head -n 1)
          URL=http://$IP
          sudo helm repo add kubera https://charts.mayadata.io/
          sudo helm repo update
          sudo helm install kubera kubera/kubera-charts --set server.url=$URL
          sleep 50
          sudo kubectl get pod 
      
